# Generated by Django 4.2.7 on 2024-04-13 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_keypair'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeyPair',
        ),
    ]
